apiVersion: v1
kind: ConfigMap
metadata:
  name: url-config
  namespace: urlshortener
data:
  go-service-url: "http://go-service.urlshortener:8000"
  python-service-url: "http://python-service.urlshortener:5000"
  go-service-base-url: "http://go-service.urlshortener:8000"
